tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/portable-ruby"

tap "beeftornado/rmtree"
tap "cantino/mcfly"
tap "heroku/brew"
tap "jmacdonald/amp"
tap "linuxbrew/xorg"
tap "rafaelgarrido/caveats"
tap "rs/tap"

brew "alerter"
brew "antigen"
brew "openssl@1.1"
brew "python@3.9"
brew "asciinema"
brew "bat"
brew "glib"
brew "pkg-config"
brew "dprint"
brew "exa"
brew "fd"
brew "libsodium"
brew "rubberband"
brew "ffmpeg"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "git-delta"
brew "gradle"
brew "hexyl"
brew "hugo"
brew "hyperfine"
brew "jql"
brew "keychain"
brew "krb5"
brew "libusb"
brew "libxml2"
brew "libxslt"
brew "llvm"
brew "neovim"
brew "nmap"
brew "node"
brew "perl"
brew "procs"
brew "ripgrep"
brew "ruby"
brew "rust-analyzer"
brew "sd"
brew "starship"
brew "subversion"
brew "tealdeer"
brew "trash-cli"
brew "xh"
brew "xxhash"
brew "youtube-dl"
brew "zellij"
brew "zoxide"
brew "zsh"


brew "cantino/mcfly/mcfly"
brew "heroku/brew/heroku"
brew "jmacdonald/amp/amp"
brew "rafaelgarrido/caveats/brew-caveats"

cask "font-cascadia-code"
cask "font-fira-mono-nerd-font"
cask "font-inconsolata-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-source-code-pro-for-powerline"

cask "bitwarden", args: { appdir: "~/Applications" }
cask "brave-browser", args: { appdir: "~/Applications" }
cask "cakebrew", args: { appdir: "~/Applications" }
cask "discord", args: { appdir: "~/Applications" }
cask "google-chrome", args: { appdir: "~/Applications" }
cask "gpg-suite-no-mail", args: { appdir: "~/Applications" }
cask "iina", args: { appdir: "~/Applications" }
cask "intellij-idea", args: { appdir: "~/Applications" }
cask "iterm2", args: { appdir: "~/Applications" }
cask "mactex", args: { appdir: "~/Applications" }
cask "netnewswire", args: { appdir: "~/Applications" }
cask "ngrok", args: { appdir: "~/Applications" }
cask "protonvpn", args: { appdir: "~/Applications" }
cask "signal", args: { appdir: "~/Applications" }
cask "suspicious-package", args: { appdir: "~/Applications" }
cask "syncthing", args: { appdir: "~/Applications" }
cask "tor-browser", args: { appdir: "~/Applications" }
cask "visual-studio-code", args: { appdir: "~/Applications" }
cask "vlc", args: { appdir: "~/Applications" }
