# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

# TODO oh my zsh template

shell = "zsh"

apply = ['defer']

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }

[plugins]

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[plugins.brew-zsh-completions]
inline = 'zsh-defer fpath+="$(brew --prefix)/share/zsh/site-functions"'

[plugins.my_functions]
local = '~/.config/zsh/personal/functions'

[plugins.my_aliases]
local = '~/.config/zsh/personal/aliases'

[plugins.bitwarden]
local = '~/.config/zsh/personal'

[plugins.starship] # why dont it work with zsh-defer?
inline = 'eval "$(starship init zsh)"'

[plugins.mcfly]
inline = 'zsh-defer eval "$(mcfly init zsh)"'

[plugins.gencomp_cache]
local = '~/.cache/gencomp'
apply = ['fpath']

[plugins.syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'

[plugins.autocomplete]
github = 'zsh-users/zsh-autosuggestions'

[plugins.mac-completions]
github = 'scriptingosx/mac-zsh-completions'

[plugins.sudo]
github = 'ohmyzsh/ohmyzsh'
dir = 'plugins/{{ name }}'

[plugins.git]
github = 'ohmyzsh/ohmyzsh'
dir = 'plugins/{{ name }}'

[plugins.zoxide]
github = 'ohmyzsh/ohmyzsh'
dir = 'plugins/{{ name }}'

[plugins.command-not-found]
github = 'ohmyzsh/ohmyzsh'
dir = 'plugins/{{ name }}'

[plugins.dotenv]
github = 'ohmyzsh/ohmyzsh'
dir = 'plugins/{{ name }}'

[plugins.gradle]
github = 'ohmyzsh/ohmyzsh'
dir = 'plugins/{{ name }}'

[plugins.clipboard]
github = 'ohmyzsh/ohmyzsh'
dir = 'lib'

[plugins.exa-aliases]
github = 'DarrinTisdale/zsh-aliases-exa'

[plugins.ping]
github = 'rummik/zsh-ing'

[plugins.colored-man]
github = 'ael-code/zsh-colored-man-pages'

[plugins.you-should-use]
github = 'MichaelAquilina/zsh-you-should-use'

[plugins.cargo-completion]
local = '~/.rustup/toolchains/stable-x86_64-apple-darwin/share/zsh/site-functions'
apply = ['fpath']

[plugins.rustup-completion]
inline = 'zsh-defer eval `rustup completions zsh rustup`'

[plugins.opam]
local = '~/.opam/opam-init/'
use = ['init.zsh']

[plugins.autoenv]
github = 'zpm-zsh/autoenv'

[plugins.virtualenv]
github = 'MichaelAquilina/zsh-autoswitch-virtualenv'

[plugins.auto-notify]
github = 'MichaelAquilina/zsh-auto-notify'

[plugins.keychain]
inline = """
zsh-defer eval `keychain --eval --quiet --noask --agents ssh,gpg 7C7ECFF562786CA6B4A8633B8AC89A889BFA44A8 CECCB3D5398F04652EF4A536109BC93C8B952313 id_rsa_github id_rsa_gitlab id_rsa_nest id_umd`
"""

# [plugins.ssh-agent]
# github = 'ohmyzsh/ohmyzsh'
# dir = 'plugins/{{ name }}'

# [plugins.gpg-agent]
# github = 'ohmyzsh/ohmyzsh'
# dir = 'plugins/{{ name }}'

# [plugins.keychain]
# github = 'ohmyzsh/ohmyzsh'
# dir = 'plugins/{{ name }}'

# [plugins.compgen]
# github = 'RobSis/zsh-completion-generator'
