# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

# TODO oh my zsh template
# empty sheldon config is 10 ms

shell = "zsh"

apply = ['defer']

[templates]
defer = """
{% for file in files %}
zsh-defer source \"{{ file }}\"\n
{% endfor %}
"""

[plugins]

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

# [plugins.history]
# local = '~/.config/zsh/personal'

# [plugins.pretty-completions]
# local = '~/.config/zsh/personal'

[plugins.brew-zsh-completions]
local = "/opt/homebrew/share/zsh/site-functions" # inlining logic makes it < 1 ms
apply = ['fpath']
# inline = 'zsh-defer fpath+="$(brew --prefix)/share/zsh/site-functions"' # 10 ms

[plugins.my_functions]
local = '~/.config/zsh/personal/functions'

[plugins.my_aliases]
local = '~/.config/zsh/personal/aliases'

[plugins.bitwarden]
local = '~/.config/zsh/personal'

# [plugins.bat]
# local = '~/.config/zsh/personal'

# [plugins.keychain] # blocking because it may ask for input
# inline = """
# eval `keychain --eval --noask --quiet --inherit any --agents ssh,gpg C6AD1D9F96B7178A99B066A849DF81AF2D28CF82 7C7ECFF562786CA6B4A8633B8AC89A889BFA44A8 CECCB3D5398F04652EF4A536109BC93C8B952313 id_rsa_github id_rsa_gitlab id_invent_kde id_rsa_nest id_umd`
# """

# Disabled cuz slow, despite being native
# [plugins.keychain] 10+ ms
# inline = "zsh-defer ssh-add --apple-use-keychain -q ~/.ssh/id_rsa_github ~/.ssh/id_rsa_gitlab ~/.ssh/id_rsa_nest"

[plugins.starship] # why dont it work with zsh-defer? 15 ms
# inline = 'eval "$(starship init zsh)"'
local = '~/.config/zsh/personal'
apply = ["source"]

[plugins.mcfly] # 10 ms
# inline = 'zsh-defer eval "$(mcfly init zsh)"'
local = '~/.config/zsh/personal'

[plugins.direnv] # 5 ms
# inline = 'zsh-defer eval "$(direnv hook zsh)"'
local = '~/.config/zsh/personal'

[plugins.fzf]
local = '/opt/homebrew/opt/fzf/shell/'
use = ['completion.zsh']

[plugins.gencomp_cache]
local = '~/.cache/gencomp'
apply = ['fpath']

[plugins.syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'

[plugins.autocomplete]
github = 'zsh-users/zsh-autosuggestions'

# disabled because it takes too long and i dont use its completions
# [plugins.extra-completions] # 5 ms
# github = 'zsh-users/zsh-completions'
# dir = 'src'
# apply = ['fpath']

[plugins.mac-completions]
github = 'scriptingosx/mac-zsh-completions'

[plugins.sudo]
github = 'ohmyzsh/ohmyzsh'
dir = 'plugins/{{ name }}'

# [plugins.git]
# github = 'ohmyzsh/ohmyzsh'
# dir = 'plugins/{{ name }}'

[plugins.gitignore]
github = 'ohmyzsh/ohmyzsh'
dir = 'plugins/{{ name }}'

[plugins.zoxide]
github = 'ohmyzsh/ohmyzsh'
dir = 'plugins/{{ name }}'

[plugins.command-not-found]
github = 'ohmyzsh/ohmyzsh'
dir = 'plugins/{{ name }}'

[plugins.gradle]
github = 'ohmyzsh/ohmyzsh'
dir = 'plugins/{{ name }}'

[plugins.clipboard]
github = 'ohmyzsh/ohmyzsh'
dir = 'lib'

[plugins.exa-aliases]
github = 'DarrinTisdale/zsh-aliases-exa'

[plugins.ping]
github = 'rummik/zsh-ing'

[plugins.colored-man]
github = 'ael-code/zsh-colored-man-pages'

[plugins.you-should-use]
github = 'MichaelAquilina/zsh-you-should-use'

[plugins.virtualenv]
github = 'MichaelAquilina/zsh-autoswitch-virtualenv'

[plugins.auto-notify]
github = 'MichaelAquilina/zsh-auto-notify'

[plugins.gencomp]
github = 'RobSis/zsh-completion-generator'

# [plugins.ssh-agent]
# github = 'ohmyzsh/ohmyzsh'
# dir = 'plugins/{{ name }}'

# [plugins.gpg-agent]
# github = 'ohmyzsh/ohmyzsh'
# dir = 'plugins/{{ name }}'

# [plugins.keychain]
# github = 'ohmyzsh/ohmyzsh'
# dir = 'plugins/{{ name }}'
