
[font]
size = 20.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[general]
# https://alacritty.org/config-alacritty.html
import = ["~/.config/alacritty/themes/default.toml"]

[window]
option_as_alt = 'Both'

