# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
bindkey -e

eval "$(/opt/homebrew/bin/brew shellenv)"
eval $(starship init zsh)
eval "$(mcfly init zsh)"

export GPG_TTY=$(tty)

fpath=(
	$(brew --prefix)/share/zsh/site-functions
	$fpath
)

zstyle :omz:plugins:ssh-agent identities id_rsa_github id_rsa_gitlab pijul_nest

GENCOMPL_FPATH=$HOME/.config/gencomp
GENCOMPL_PY=python3

eval "$(sheldon source)"

autoload -Uz compinit && compinit

export EDITOR='code --wait'
export VISUAL='code --wait'
