# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '$HOME/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

source /home/linuxbrew/.linuxbrew/share/antigen/antigen.zsh
antigen use oh-my-zsh
# zstyle :omz:plugins:ssh-agent identities id_rsa_github id_rsa_gitlab
# antigen theme hybras/Arity-Zsh-Theme

antigen bundles <<EOBUNDLES
	zsh-users/zsh-syntax-highlighting
	zsh-users/zsh-autosuggestions
	sudo
	git
	python
#	gradle
	ssh-agent
#	nmap
#	pip
	command-not-found
	zpm-zsh/clipboard
	DarrinTisdale/zsh-aliases-exa
	RobSis/zsh-completion-generator
	rummik/zsh-ing
	robertzk/send.zsh
	dotenv
	$HOME/Documents/dotfiles grace --no-local-clone
	$HOME/Documents/dotfiles brew --no-local-clone
EOBUNDLES

GENCOMPL_FPATH=$HOME/.config/gencomp
GENCOMPL_PY=python3

antigen apply

autoload -U compinit && compinit

export EDITOR='nvim'
export VISUAL='nvim'

export LSCOLORS=ExFxBxDxCxegedabagacad

# /Library/Apple/usr/bin:/Library/Apple/bin:/Library/TeX/texbin:/usr/local/go/bin:
path=(
	#Rust
	"$HOME/.cargo/bin"
	#Java
	"/home/linuxbrew/.linuxbrew/opt/openjdk/bin"
	#Ruby
	"/home/linuxbrew/.linuxbrew/opt/ruby@2.7/bin"
	"/home/linuxbrew/.linuxbrew/lib/ruby/gems/3.0.0/bin"
	$path
)


export PATH

eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
eval $(starship init zsh)
eval "$(mcfly init zsh)"

export GPG_TTY=$(tty)

eval $(keychain --eval --agents ssh,gpg id_rsa_github id_rsa_gitlab pijul_nest github gitlab)

# opam configuration
test -r $HOME/.opam/opam-init/init.zsh && . $HOME/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
