# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/hybras/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

source /home/linuxbrew/.linuxbrew/share/antigen/antigen.zsh
antigen use oh-my-zsh

# antigen theme hybras/Arity-Zsh-Theme

antigen bundles <<EOBUNDLES
	zsh-users/zsh-syntax-highlighting
	zsh-users/zsh-autosuggestions
	sudo
	git
	python
#	gradle
	ssh-agent
#	nmap
#	pip
	command-not-found
	zpm-zsh/clipboard
	DarrinTisdale/zsh-aliases-exa
	RobSis/zsh-completion-generator
	rummik/zsh-ing
	robertzk/send.zsh
	dotenv
EOBUNDLES

GENCOMPL_FPATH=$HOME/.config/gencomp
GENCOMPL_PY=python3

antigen apply

autoload -U compinit && compinit

export EDITOR='nvim'
export VISUAL='nvim'

export LSCOLORS=ExFxBxDxCxegedabagacad

# /Library/Apple/usr/bin:/Library/Apple/bin:/Library/TeX/texbin:/usr/local/go/bin:
path=(
	#Current Directory
	"."
	#Rust
	"$HOME/.cargo/bin"
	# homebrew openjdk
	"/home/linuxbrew/.linuxbrew/opt/openjdk@11/bin"
	"/home/linuxbrew/.linuxbrew/lib/ruby/gems/2.7.0/bin"
	$path
)


export PATH
local alias_files="$HOME/Documents/dotfiles/aliases.zsh"
if [[ -x $alias_files ]]; then
	source $alias_files
fi

eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
eval $(starship init zsh)

